name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        env:
          qscore: ${{ secrets.QSCORED_API_KEY }}
          PAT: ${{ secrets.PAT }}
      - name: Download DesigniteJava
        run: wget "https://www.designite-tools.com/static/download/DJE/DesigniteJava.jar"

      - name: Analyze project with DesigniteJava
        run: |
          java -jar DesigniteJava.jar -ci -repo $GITHUB_REPOSITORY -pat {{ env.PAT }} 
          ls
          curl -X PUT -H "Authorization: Token {{ env.qscore }}" -H "repository-link:https://github.com/" + ${{ github.repository }}-H "username:" -H "Content-Type: mulitpart/form-data" --url "https://qscored.com/api/upload/file.xml?is_open_access=on&version=$GITHUB_RUN_NUMBER&project_name=hello" -F "file=@Designite_output/DesigniteAnalysis.xml"
